### PR TITLE
Update License

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@stefdoerr I did not find you license type on https://spdx.org/licenses/ so I listed it as `OTHER`.

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by stefdoerr** [comment]
I think instead of `OTHER` `LicenseRef-HTMD` is more standard

**Comment by stefdoerr** [comment]
I think the `LICENSE` file should still be there in the recipe, since it's mentioned in `license_file` attribute. Also because those LicenseRef are not standard it's best to ship the license with the package otherwise it's hard for the users to find it

**Comment by jan-janssen** [comment]
> I think the `LICENSE` file should still be there in the recipe, since it's mentioned in `license_file` attribute. Also because those LicenseRef are not standard it's best to ship the license with the package otherwise it's hard for the users to find it

The `LICENSE` file is used from the pypi package

**Comment by stefdoerr** [comment]
Do we need a re-render for the license name to appear in the README correctly?

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Review by stefdoerr — APPROVED** [review]

**Comment by stefdoerr** [comment]
Sorry for all these questions but I'm new to conda-forge. Will this also fix the license mentioned here? https://anaconda.org/conda-forge/moleculekit

Can we remove old releases on anaconda since their license is wrong?

**Pull request merged**
